version: '3'

services:
  db_postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_ROOT_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
      restart: always

  django_app:
    build:
      context: ./backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_CONTAINER_NAME}
      TZ: ${TZ}
    volumes:
      - ./backend/microservices_example:/app
    depends_on:
      - db_postgres
    working_dir: /app
    command: sh run.sh
    ports:
      - "8000:8000"

volumes:
  postgres_data: