# Generated by Django 4.1 on 2022-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
