# Generated by Django 4.1 on 2022-10-22 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_email_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
